//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen_Empelado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empelados
    {
        public int id_Empelado { get; set; }
        public string Nombre { get; set; }
        public string ApPaterno { get; set; }
        public string ApMaterno { get; set; }
        public string NumEpleado { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string fechaNac { get; set; }
        public Nullable<int> Id_Estado { get; set; }
    
        public virtual Estados Estados { get; set; }
    }
}
